models:
  gpt-4o:
    api_key: OPENROUTER_API_KEY
    base_url: OPENROUTER_API_BASE
    max_context: 128000

  gpt-3.5-turbo:
    api_key: OPENROUTER_API_KEY
    base_url: OPENROUTER_API_BASE
    max_context: 16000

  # H100 GPU
  dnotitia/DNA-2.0-0.6B:
    api_key: LOCAL_API_KEY
    base_url: LOCAL_API_BASE
    max_context: 27000

  HuggingFaceTB/SmolLM2-1.7B-Instruct:
    api_key: LOCAL_API_KEY
    base_url: LOCAL_API_BASE
    max_context: 7680
    max_tokens: 512

  HuggingFaceTB/SmolLM3-3B:
    api_key: LOCAL_API_KEY
    base_url: LOCAL_API_BASE
    max_context: 27000
    max_tokens: 1024
